### ISSUE TITLE
[Question]: How i can attach UnityExplorerEditor in Among us 2023.6.13

### ISSUE THREAD

**Issue by Wael1231** [yukieiji/UnityExplorer#2]
### Describe the issue

hey i am an Among us modder i wante really change something in Among us to make it better how i can attach the Editor in UnityExplorer in MainMenu and MMOnline ?

**Comment by Wael1231** [comment]
i mean Unity Editor

**Comment by yukieiji** [comment]
I can't answer that because this is the UnityExplorer repository, not the UnityEditor repository

**Comment by Wael1231** [comment]
@yukieiji  i mean this https://github.com/yukieiji/UnityExplorer/tree/master/UnityEditorPackage
