### ISSUE TITLE
[Enhancement]: list the changes/improvements of this over sinai's unity explorer

### ISSUE THREAD

**Issue by krispyking24** [yukieiji/UnityExplorer#24]
### Describe the new feature or enhancement

list the changes/improvements of this over sinai's unity explorer other than that this is still being worked on

**Comment by yukieiji** [comment]
?

**Comment by krispyking24** [comment]
i think the title is self explanatory could u say where i could fix the confusion?

**Comment by yukieiji** [comment]
If you look at the differences in the README, you'll see that basically all I do fixing bugs.
There are no behavior changes, no major improvements

Conversely, what features do you want?

**Comment by krispyking24** [comment]
oh im sorry i didnt see that, i don't know maybe make persistent changes possible like on scene reload the changes u made previously carry over?

**Comment by yukieiji** [comment]
> oh im sorry i didnt see that

You're right, it was hard to understand. I'll add it to the README.

> i don't know maybe make persistent changes possible like on scene reload the changes u made previously carry over? or to make custom keybinds for actions which the player can hit even when the menu is closed

If you really want it, can you create a separate ticket with the details.
