### ISSUE TITLE
[Help]: Doesn't start with another mod

### ISSUE THREAD

**Issue by BlackRockSoul** [yukieiji/UnityExplorer#3]
Maybe it has nothing to do with Unity Explorer, which works fine on its own, but won't start with another mod.

Both of them just didn't start for some reason.

If it has nothing to do with UnityExplorer, you could just close the issue. But maybe someone knows how to fix it.

![image](https://github.com/yukieiji/UnityExplorer/assets/4317830/b3f89dcb-cb08-46e0-8dc0-b384db2addd1)

**Comment by yukieiji** [comment]
Please tell us more about your environment
Which version of BepInEx are you using, OS, game, type of UE you are using(Il2Cpp?CoreCLR?), etc.

**Comment by BlackRockSoul** [comment]
Windows 11, using the `BIE 6.X (CoreCLR, be.647+)` UE, BepInEx was compiled from `master` branch.

Seems like I realized that UE and the mod using two different `UniverseLib.IL2CPP.Interop.dll` so I just override it from UE and it started.

But there's a different issue now. When I try to search by class it throws a new error
![image](https://github.com/yukieiji/UnityExplorer/assets/4317830/27959db2-9fa1-4333-af40-94481936368f)

**Comment by yukieiji** [comment]
Wait a minute. Which mod are you going to use with UE?
My UniverseLib has been updated with some bug fixes, so if your mod requires UniverseLib, you will have to recompile etc. depending on that.

**Comment by BlackRockSoul** [comment]
>Wait a minute. Which mod are you going to use with UE?

Trying to bypass a license check on a paid bot with my zero C# and Unity skills lmao. If it's too off topic feel free to close.

Was planning to just find a class and toggle something on but it started to be too complicated on a moment when original UE didn't work. Finally started this version but stuck again.

**Comment by BlackRockSoul** [comment]
Yeah okay, thanks for your help and sorry for bothering!
Seems like it has nothing with UE itself and its everything about SmartAssembly and so on. Will keep learning :)
