### ISSUE TITLE
[Enhancement]: Allow re-loading of UE when destroyed

### ISSUE THREAD

**Issue by notunixian** [yukieiji/UnityExplorer#30]
### Describe the new feature or enhancement

I've experienced in a few unity games that their loading screen or whatever they do in the background would result in UE being destroyed (for example, loading a different level in said game results in UE being destroyed). If there could be a hotkey or automatic detection of UE being destroyed and force a re-initialization that would solve this problem.

Ways I think this could be done:
1. Mentioned before, using a hotkey to re-load UnityExplorer if the user sees that it's been destroyed
2. Using a coroutine or check on Update to see the state of UE and re-load if it's been destroyed (i haven't looked into the source of UE, so this might not be possible or too demanding to pull off).

If there are other ways that would work that I didn't mention above, that'd work too. 
I may spend some time trying to create a solution and create a pull request if I do create one, until then, I've decided to make this issue.

**Comment by yukieiji** [comment]
What does it mean that the UE is destroyed?
Does it mean that the UE menu will be hidden? Or is it the result of some protection feature on the game side that causes the UE to stop working?

Also, if it stops working when the game loads, the following sections may be helpful
https://github.com/yukieiji/UnityExplorer?tab=readme-ov-file#common-issues-and-solutions

**Comment by yukieiji** [comment]
> The menu becomes completely hidden, pressing F7 will unlock the cursor but nothing shows

If this is true, then [this process](https://github.com/yukieiji/UnityExplorer/blob/aa3030ab0d6b28a45f13539a9a25e7f689be3c35/src/UI/UIManager.cs#L64) has been reached, indicating that the UI itself has not been destroyed.

I feel this is more of a issue than a enhancement, please give me the game where this occurs and log

**Comment by yukieiji** [comment]
> If this is true, then [this process](https://github.com/yukieiji/UnityExplorer/blob/aa3030ab0d6b28a45f13539a9a25e7f689be3c35/src/UI/UIManager.cs#L64) has been reached, indicating that the UI itself has not been destroyed.

This leads me to believe that implementing the proposed feature will not work

So can you please tell me which game caused the problem so that I can investigate the detailed cause, etc.?
If you don't reply, I will close this ticket.

**Comment by ausernamewowwie** [comment]
Hello, I have an issue similar to this. When logging out to switch accounts in the game, all of the text of the UI disappears, but the windows are still there and I can still interact with them.

**Comment by yukieiji** [comment]
> Hello, I have an issue similar to this. When logging out to switch accounts in the game, all of the text of the UI disappears, but the windows are still there and I can still interact with them.

Can you please tell the game and attach the execution log of the game?
And when I press F7, does it behave the same as this ticket?

**Comment by yukieiji** [comment]
Currently, there is too less info to do anything about it.
If I don't receive a reply from either of you, I will close it.

**Comment by yukieiji** [comment]
Closed due to no reply
