### ISSUE TITLE
[Bug]: UnityExplorer load but game freezes upon trying to load assets(Party Animals)

### ISSUE THREAD

**Issue by RedWideWeb** [yukieiji/UnityExplorer#34]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

- [X] Yes, work fine!!

### Which release are you using?

BepInEx Unity IL2CPP CoreCLR

### Which game did this occur on?

Party Animals v 1.18.13.0 (Steam)

[Message: Preloader] BepInEx 6.0.0-be.697 - PartyAnimals
[Message: Preloader] Built from commit 53625800b86f6c68751445248260edf0b27a71c2
[Info   :   BepInEx] System platform: Windows 10 64-bit
[Info   :   BepInEx] Process bitness: 64-bit (x64)
[Info   :   BepInEx] Running under Unity 2021.3.5f1
[Info   :   BepInEx] Runtime version: 6.0.7
[Info   :   BepInEx] Runtime information: .NET 6.0.7

### Describe the issue.

Game Loads. UnityExplorer initialises. After a bit of time it just freezes. Usually at 53% (Game). But only once it happende to load until 92% and then froze. Maybe I am doing something wrong but please help me understand so I test further. It's my first time doing so. MelonLoaded 0.6.6 has similar behavior. Game loads and then freezes. Game also gives "The memory could not be read" immediately but if I don't touch it - game runs fine.

[Player.log](https://github.com/user-attachments/files/17992123/Player.log)
[LogOutput.log](https://github.com/user-attachments/files/17992130/LogOutput.log)

**Comment by RedWideWeb** [comment]
[UnityExplorer.MelonLoader.IL2CPP](https://github.com/yukieiji/UnityExplorer/releases/download/v4.12.2/UnityExplorer.MelonLoader.IL2CPP.zip) with Melon 0.5.7 works better. Game loads. All assets load. UnityExplorer UI is visible. But just as the game is about to load main menu I see "Preferences saved!" in the console and everything just closes

[Latest.log](https://github.com/user-attachments/files/17992303/Latest.log)
[Player.log](https://github.com/user-attachments/files/17992318/Player.log)

**Comment by yukieiji** [comment]
Since this game has PvP and store elements, it is very likely that some anti-cheat is running, I don't think UE would work under those circumstances.

> Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)
 Yes, work fine!!

Really? Please let me know which mods are working.

**Comment by RedWideWeb** [comment]
@yukieiji but please tell me at least which versions to test with which loader version

**Comment by yukieiji** [comment]
Any loader is fine, as long as it works with mods that have access to GameObject, etc..

**Comment by yukieiji** [comment]
> Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)

The reason I'm asking this is because if the mod's code is publicly available, I can use it as a reference

**Comment by RedWideWeb** [comment]
> Since this game has PvP and store elements, it is very likely that some anti-cheat is running, I don't think UE would work under those circumstances.
> 
> > Will other mods work? (Not mods that change settings, but small mods that access game objects, etc.)
> > Yes, work fine!!
> 
> Really? Please let me know which mods are working.

Well I will be honest I didn’t try when I created the issue but now I did. I took TestMod from GitHub, loaded all the assemblies and was able to manipulate my player. Set max health and call functions in runtime. Maybe you are right and they have implemented a security measure against UnityExplorer specifically but not against Melon and all mods.

**Comment by yukieiji** [comment]
I understand that there is a mod that works.
But sadly, I found out that they are against the game's terms of service.
So, I will not do anything about this ticket myself, I will not provide technical support, please don't send me mod links, etc.

**Comment by RedWideWeb** [comment]
What do you it's against ToS? All games ToS is against modding (almost). But UnityExplorer still exist

**Comment by yukieiji** [comment]
UE exists, but it is up to each individual to decide how to develop and use it.
To deal with this I need to hack the game, if I don't have to hack the game, I will deal with it, but I don't want to be criminals by hacking the game.

**Comment by yukieiji** [comment]
You are free to deal with this on your own, but do not rely on me.
