### ISSUE TITLE
[Bug]: Unity Explorer is not being recognized

### ISSUE THREAD

**Issue by alan42521** [yukieiji/UnityExplorer#6]
### Are you on the latest version of UnityExplorer?

- [X] Yes, I'm on the latest version of UnityExplorer.

### Which release are you using?

BepInEx 6.X Mono

### Which game did this occur on?

build

### Describe the issue.

When I install the unity explorer in 6.0.0-be.682,the unity explorer can not be recognized,it just says 0 plugins loaded.It seems like the beplnex 6.0 for mono version also has the problem as il2cpp

**Comment by alan42521** [comment]
![Uploading 捕获.PNG…]()

**Comment by yukieiji** [comment]
Don't close when the fixing isn't complete.

Will this work?
[UnityExplorer.BepInEx6.Unity.Mono.zip](https://github.com/yukieiji/UnityExplorer/files/13763738/UnityExplorer.BepInEx6.Unity.Mono.zip)

**Comment by alan42521** [comment]
It works!Thanks

**Comment by yukieiji** [comment]
fixed in [v4.11.0](https://github.com/yukieiji/UnityExplorer/releases/tag/v4.11.0)
